download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/nginxinc-nginx_core-0.8.0.tar.gz
format_version: 1.0.0
name: nginx_core
namespace: nginxinc
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.8.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/nginxinc/nginx_core/versions/0.8.0/
