---
- hosts: node1
  gather_facts: no
  tasks:
    - name: Create custom fact on node1
      blockinfile:
        path: /etc/ansible/facts.d/local.fact
        create: true
        block: |
          [localfacts]
          type: production
- hosts: node2
  gather_facts: no
  tasks:
    - name: Create custom fact on node2
      blockinfile:
        path: /etc/ansible/facts.d/local.fact
        create: true
        block: |
          [localfacts]
          type: testing

