---
- name: conditionals test
  hosts: node1
  vars:
    package: nmap
  tasks:
  - name: install vsftpd if sufficient space on /boot
    package:
      name: "{{ package }}"
      state: latest
    loop: "{{ ansible_mounts }}"
    when: item.mount == "/boot" and item.size_available > 100000000
    register: result
  - name: debug
    debug:
      var: result
