---
- name: test register
  hosts: node1
  vars_prompt:
    - name: username
      prompt: what username u want
      private: no
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug:
        var: passwd_contents
    - debug:
        msg: echo "passwd contain user {{ username }}"
      when: passwd_contents.stdout.find(username) != -1
