---
- name: create user using a variable
  hosts: node1
  vars_files:
    - vault/vault
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"
      register: task_result
    - name: show the result
      debug:
        var: task_result
    - name: using debug to show password
      debug:
        msg: the password is {{ pwhash }}
    - name: generating encrypted password
      shell: echo {{ pwhash }} | passwd --stdin {{ user }}


