---
- name: create user using a variable
  hosts: node1
  vars_files:
    - users
  tasks:
    # - name: using debug
    - debug:
        msg: 
         - first username is {{ inventory_hostname }}
         - second username is {{ inventory_hostname }}
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"
      


