---
- name: httpd services need to be stop
  hosts: node1
  tasks:
    - name: stopped httpd services if running
      service:
        name: nginx
        state: stopped
        enabled: false
      register: result_serv
    - name: debug
      debug:
        var: result_serv
